### ISSUE TITLE
thinkphp6框架引用，怎么显示Class "Hedeqiang\TenIM\IM" not found

### ISSUE THREAD

**Issue by yeshili** [hedeqiang/IM#18]
直接按照你的手册来，下载，然后引入调用，就出现Class "Hedeqiang\TenIM\IM" not found不存在，本地可以招到，到了服务器就找不到这类！

**Comment by yeshili** [comment]
![Uploading image.png…]()

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183583133-bae0c395-9b18-402e-9669-99fbe282e1be.png)
![image](https://user-images.githubusercontent.com/24773628/183583149-2caf5d74-e46f-49d0-9a05-b7cc9fe22a5f.png)
![image](https://user-images.githubusercontent.com/24773628/183583179-3fcc2238-eaca-43dd-aebc-4e68636a6cdb.png)

**Comment by houseme** [comment]
处理一下composer的缓存

**Comment by yeshili** [comment]
跟composer没关系呢，服务器上是没有安装composer呢，本地下载安装好了，就直接更新到服务器上呢。

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183584884-9254cc52-7e47-4f41-8b64-4dbcb875da7c.png)
![image](https://user-images.githubusercontent.com/24773628/183584973-aa5d4d67-e9e8-4bd1-99be-f482c483361c.png)

**Comment by yeshili** [comment]
我直接这样子测试，也还是这样子，下载其他的扩展包都没问题呢，第一次出现这种情况！！

**Comment by houseme** [comment]
> 我直接这样子测试，也还是这样子，下载其他的扩展包都没问题呢，第一次出现这种情况！！

可以确定项目在服务器和本地机器的路径是一致的吗？

你可以看看 `vender/composer/autoload_classmap.php` 文件,这个文件 是不是一致，或许你上传了吗

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183585853-2fcc724a-4610-447d-a634-114c3de85fd9.png)
![image](https://user-images.githubusercontent.com/24773628/183585947-c6cbb952-3072-441e-b78a-c12dbbf6330a.png)
一致呢

**Comment by yeshili** [comment]
还有，我的php版本是8.0的

**Comment by yeshili** [comment]
可以了，这边被禁止一传送然后就被删除了，心碎，谢谢。

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183827854-1915f994-7c8f-4059-9a92-1690dfa7407b.png)
你好，这个希望加上这个

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183829193-7d907c22-2395-41d1-b2a5-e1b13b7f03c5.png)
我直接改了下
![image](https://user-images.githubusercontent.com/24773628/183829265-b836454f-f678-42ff-bc57-0c8d20036035.png)
就可以直接外部调用了，就是以后升级就会被覆盖。

**Comment by houseme** [comment]
> ![image](https://user-images.githubusercontent.com/24773628/183829193-7d907c22-2395-41d1-b2a5-e1b13b7f03c5.png) 我直接改了下 ![image](https://user-images.githubusercontent.com/24773628/183829265-b836454f-f678-42ff-bc57-0c8d20036035.png) 就可以直接外部调用了，就是以后升级就会被覆盖。

兄弟，要不提一个pr?

**Comment by yeshili** [comment]
![image](https://user-images.githubusercontent.com/24773628/183844764-7e475535-0d25-485d-aaef-4ebd7e802549.png)
这个我觉得不太合理呢，错误存在，不应该直接组合字符串返回，应该，让用户直接拿到错误编码自己去处理！

**Comment by houseme** [comment]
> ![image](https://user-images.githubusercontent.com/24773628/183844764-7e475535-0d25-485d-aaef-4ebd7e802549.png) 这个我觉得不太合理呢，错误存在，不应该直接组合字符串返回，应该，让用户直接拿到错误编码自己去处理！

可以一起提pr

**Comment by hedeqiang** [comment]
这其实应该算异常 异常我是直接 throw 出去了
