### ISSUE TITLE
腾讯IM返回格式有变动啦

### ISSUE THREAD

**Issue by rakuchyan** [hedeqiang/IM#20]
腾讯IM返回包已经不存在 ActionStatus
代码地址：\Hedeqiang\TenIM\IM::send  line:61
现在返回格式是：array ( 'ErrorCode' => 0, 'ErrorInfo' => '', )
求求可以改嘛

**Comment by houseme** [comment]
欢迎提pr，建议加上文档地址哦

**Comment by hedeqiang** [comment]
我看文档返回还是 
```
{
  "ActionStatus": "OK", 
  "ErrorInfo": "", 
  "ErrorCode": 0, 
  "MsgTime": 1572870301,
  "MsgKey": "89541_2574206_1572870301"
}

```
@rakuchyan

**Comment by hedeqiang** [comment]
刚发了一版本 v2.0.0,这一版本由用户来进行校验，直接返回腾讯云的数据
