### ISSUE TITLE
send返回值问题

### ISSUE THREAD

**Issue by dino-ma** [hedeqiang/IM#3]
您好，很感谢您的im包。很快的完成了对接。
但是在send 方法判断返回值的时候，只需要判断code 不需要判断ActionStatus 有一些接口只有code没有ActionStatus 这样会造成意外的抛异常，建议修改一下。3q

**Comment by hedeqiang** [comment]
@dino-ma  提个 PR 吧

**Comment by hedeqiang** [comment]
@dino-ma 您能说下哪些接口 没有 `ActionStatus` 吗？

**Comment by hedeqiang** [comment]
暂时先关闭了
