### ISSUE TITLE
建议按照语义化版本的规则来更新版本号

### ISSUE THREAD

**Issue by Sy-Dante** [hedeqiang/IM#7]
按照语义化版本规范的话，增加了 ServiceProvider 和 Facades 应当是更新次版本号。

> 版本格式：主版本号.次版本号.修订号，版本号递增规则如下：
> 
> 主版本号：当你做了不兼容的 API 修改，
> 次版本号：当你做了向下兼容的功能性新增，
> 修订号：当你做了向下兼容的问题修正。

参考文档：https://semver.org/lang/zh-CN/

**Comment by hedeqiang** [comment]
感谢建议

**Comment by hedeqiang** [comment]
打了一个版本，之前的暂时不动了，我怕别人有使用，造成麻烦，
